#!/usr/bin/env python3
"""Shared fail-closed tooling for the three Phase 6.6 provider canaries.

This module intentionally contains no AWS or Printify client.  A separately reviewed live adapter
may implement :class:`ProviderAcceptanceBackend` and return the exact durable records and provider
call observations defined here.  The shared boundary validates both independent gate files before
constructing that backend, proves the frozen gate-specific behavior, reduces all identifiers to
run-scoped SHA-256 digests, and writes only create-only private evidence.
"""

from __future__ import annotations

import json
import os
import re
import secrets
import stat
from collections import Counter
from collections.abc import Callable, Iterator, Mapping, Sequence
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from enum import StrEnum
from hashlib import sha256
from pathlib import Path
from typing import Annotated, Any, Final, Literal, Protocol

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictInt,
    StringConstraints,
    ValidationError,
    field_validator,
    model_validator,
)

from mr_lister.acceptance.evidence_set import Phase66ArtifactFile
from mr_lister.acceptance.phase6 import (
    AcceptanceEvidenceClass,
    AcceptanceOutcome,
    ArtifactFormat,
    ArtifactKind,
    ProviderFinalState,
    ProviderGateId,
    phase66_acceptance_manifest,
    phase66_manifest_digest,
    validate_phase66_evidence,
)
from mr_lister.control.fingerprints import canonical_fingerprint, product_sync_record_fingerprint
from mr_lister.control.models import (
    AgentPreparationEvidence,
    ArtworkAnalysisRecord,
    CancellationDecisionRecord,
    CommandReceipt,
    ControlJobRecord,
    ControlJobState,
    OwnerId,
    ProductSyncRecord,
    ProviderCallPermit,
    ProviderCallPermitStatus,
    ReviewDecision,
    ReviewDecisionRecord,
    SafeId,
    SourceArtifactRecord,
    WorkRequest,
    WorkRequestStatus,
    WorkType,
)
from mr_lister.production.provider_resources import ProviderRequestAuditRecord
from tools import capture_phase66_agentcore_deployment_authority as agentcore_capture
from tools import capture_phase66_deployment_authority as deployment_capture

REPOSITORY_ROOT: Final = Path(__file__).resolve().parents[1]
PRIVATE_ROOT: Final = REPOSITORY_ROOT / ".mr_lister_private" / "phase66-acceptance"

GATE_AUTHORITY_FORMAT: Final = "phase6.6-provider-gate-authority-v1"
OBSERVATION_FORMAT: Final = "phase6.6-sanitized-provider-observation-v1"
LEDGER_FORMAT: Final = "phase6.6-sanitized-provider-call-ledger-v1"
SUMMARY_FORMAT: Final = "phase6.6-sanitized-provider-canary-summary-v1"
LOG_AUDIT_FORMAT: Final = "phase6.6-sanitized-provider-log-audit-v1"
MAX_AUTHORITY_WINDOW: Final = timedelta(hours=1)
MAX_INPUT_BYTES: Final = 8 * 1024 * 1024
PRIMARY_SOURCE_BYTES: Final = 5 * 1024 * 1024

_DIGEST = re.compile(r"^[a-f0-9]{64}$")
_TIMESTAMP = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")
_PROVIDER_GATES: Final = (
    "provider.primary_same_job_canary",
    "provider.concurrency_canary",
    "provider.cancellation_canary",
)
_CLOSURE_FUNCTIONS: Final = {
    "PreparationDispatchFunction",
    "ProviderDraftFunction",
    "UploadApiFunction",
}
_EXPECTED_LIMITS: Final = {
    "provider.primary_same_job_canary": (1, 1, 2),
    "provider.concurrency_canary": (1, 1, 1),
    "provider.cancellation_canary": (0, 0, 0),
}
_EXPECTED_CALLER_DIGEST: Final = sha256(
    agentcore_capture.EXPECTED_CALLER_ARN.encode("ascii")
).hexdigest()

type Digest = Annotated[str, StringConstraints(pattern=r"^[a-f0-9]{64}$")]
type CanonicalTimestamp = Annotated[
    str,
    StringConstraints(pattern=r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$"),
]


class ProviderAcceptanceError(RuntimeError):
    """A provider-canary authority, observation, or output failed closed."""


class _ClosedModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class ProviderGateKind(StrEnum):
    RUN = "run_gate"
    WRITE = "provider_write_gate"


class ProviderCommandName(StrEnum):
    REVISE = "revise"
    APPROVE = "approve"
    CANCEL = "cancel"


class ProviderCommandOutcome(StrEnum):
    WON = "won"
    CONFLICT = "conflict"


class ProviderGateAuthority(_ClosedModel):
    """One independently supplied exact authorization file; never generated by this module."""

    format: Literal["phase6.6-provider-gate-authority-v1"]
    gate_id: ProviderGateId
    gate_kind: ProviderGateKind
    issued_at: CanonicalTimestamp
    expires_at: CanonicalTimestamp
    deployment_digest: Digest
    deployment_authority_sha256: Digest
    agentcore_authority_digest: Digest
    agentcore_authority_sha256: Digest
    source_commit_digest: Digest
    principal_digest: Digest
    prerequisite_run_digests: tuple[Digest, ...] = Field(max_length=12)
    approved_scope: Literal["unpublished_draft_create_update_only"]
    approved_max_artwork_uploads: StrictInt = Field(ge=0, le=1)
    approved_max_product_posts: StrictInt = Field(ge=0, le=1)
    approved_max_product_puts: StrictInt = Field(ge=0, le=2)
    root_credentials_rejected: Literal[True]
    publication_capability_absent: Literal[True]
    nonce_digest: Digest

    @field_validator(
        "root_credentials_rejected",
        "publication_capability_absent",
        mode="before",
    )
    @classmethod
    def exact_boolean_attestations(cls, value: object) -> object:
        if type(value) is not bool:
            raise ValueError("Provider gate attestations must be exact booleans")
        return value

    @model_validator(mode="after")
    def gate_scope_is_exact(self) -> ProviderGateAuthority:
        if self.gate_id not in _PROVIDER_GATES:
            raise ValueError("Provider gate authority names an unsupported gate")
        issued = _parse_timestamp(self.issued_at)
        expires = _parse_timestamp(self.expires_at)
        if expires <= issued or expires - issued > MAX_AUTHORITY_WINDOW:
            raise ValueError("Provider gate authority window is invalid")
        expected = _EXPECTED_LIMITS[self.gate_id]
        actual = (
            self.approved_max_artwork_uploads,
            self.approved_max_product_posts,
            self.approved_max_product_puts,
        )
        if actual != expected or self.principal_digest != _EXPECTED_CALLER_DIGEST:
            raise ValueError("Provider gate authority scope is not exact")
        return self


class ProviderLiveCall(_ClosedModel):
    """Identifier-bearing live call fact kept in memory until sanitization."""

    ordinal: StrictInt = Field(ge=1, le=200)
    audit: ProviderRequestAuditRecord
    status_code: Literal[200, 201]
    attempt_id: SafeId | None = None
    work_request_id: SafeId | None = None
    product_id: SafeId | None = None

    @model_validator(mode="after")
    def call_shape_matches_route(self) -> ProviderLiveCall:
        mutation = self.audit.method in {"POST", "PUT"}
        if mutation != (self.attempt_id is not None and self.work_request_id is not None):
            raise ValueError("Provider mutation must bind one permit and work request")
        product_route = self.audit.path in {
            "/v1/shops/{shop_id}/products.json",
            "/v1/shops/{shop_id}/products/{product_id}.json",
        }
        if product_route != (self.product_id is not None):
            raise ValueError("Product calls must bind exactly one product identity")
        if self.audit.outcome != "allowed":
            raise ValueError("Rejected provider attempts cannot enter a passing live result")
        return self


class CommandRaceObservation(_ClosedModel):
    name: ProviderCommandName
    outcome: ProviderCommandOutcome
    actor_owner_id: OwnerId
    expected_record_version: StrictInt = Field(ge=0)


class FinalProductObservation(_ClosedModel):
    product_id: SafeId
    payload_fingerprint: Digest
    provider_locked: Literal[False]
    provider_published: Literal[False]

    @field_validator("provider_locked", "provider_published", mode="before")
    @classmethod
    def safe_state_is_exact_boolean(cls, value: object) -> object:
        if type(value) is not bool:
            raise ValueError("Final provider state must use exact booleans")
        return value


class ProviderLiveResult(_ClosedModel):
    """Exact in-memory response required from a separately reviewed live adapter."""

    gate_id: ProviderGateId
    observed_at: AwareDatetime
    aws_caller_arn: str = Field(min_length=1, max_length=512)
    seller_actor_owner_id: OwnerId
    seller_command_channel: StrictBool
    job: ControlJobRecord
    source_artifact: SourceArtifactRecord | None = None
    work_requests: tuple[WorkRequest, ...] = Field(max_length=64)
    artwork_analysis: ArtworkAnalysisRecord | None = None
    agent_evidence: AgentPreparationEvidence | None = None
    agentcore_correlation_id: str | None = Field(
        default=None,
        pattern=r"^[a-f0-9]{24}$",
    )
    gemma_inference_count: StrictInt = Field(default=0, ge=0, le=4)
    product_sync: ProductSyncRecord | None = None
    final_product: FinalProductObservation | None = None
    provider_call_permits: tuple[ProviderCallPermit, ...] = Field(max_length=32)
    provider_calls: tuple[ProviderLiveCall, ...] = Field(max_length=200)
    command_outcomes: tuple[CommandRaceObservation, ...] = Field(max_length=8)
    command_receipts: tuple[CommandReceipt, ...] = Field(max_length=8)
    review_decisions: tuple[ReviewDecisionRecord, ...] = Field(max_length=8)
    cancellation_decisions: tuple[CancellationDecisionRecord, ...] = Field(max_length=8)
    source_size_bytes: StrictInt | None = Field(default=None, gt=0)
    running_execution_count: StrictInt = Field(ge=0, le=100)
    administrator_action_count: StrictInt = Field(ge=0, le=100)
    root_action_count: StrictInt = Field(ge=0, le=100)
    publication_attempt_count: StrictInt = Field(ge=0, le=100)
    order_attempt_count: StrictInt = Field(ge=0, le=100)
    fulfillment_attempt_count: StrictInt = Field(ge=0, le=100)
    work_inventory_complete: Literal[True]
    permit_inventory_complete: Literal[True]
    execution_inventory_complete: Literal[True]
    command_inventory_complete: Literal[True]

    @field_validator(
        "work_inventory_complete",
        "permit_inventory_complete",
        "execution_inventory_complete",
        "command_inventory_complete",
        mode="before",
    )
    @classmethod
    def inventory_flags_are_exact_booleans(cls, value: object) -> object:
        if type(value) is not bool:
            raise ValueError("Provider inventories require exact boolean attestations")
        return value


class SanitizedProviderCall(_ClosedModel):
    ordinal: StrictInt = Field(ge=1, le=200)
    method: Literal["GET", "POST", "PUT"]
    path: str = Field(min_length=1, max_length=160)
    status_code: Literal[200, 201]
    attempt_digest: Digest | None = None
    work_digest: Digest | None = None
    product_digest: Digest | None = None

    @model_validator(mode="after")
    def method_and_path_are_one_audited_route(self) -> SanitizedProviderCall:
        try:
            ProviderRequestAuditRecord(method=self.method, path=self.path)
        except ValueError:
            raise ValueError("Sanitized provider call is outside the audited route set") from None
        mutation = self.method in {"POST", "PUT"}
        if mutation != (self.attempt_digest is not None and self.work_digest is not None):
            raise ValueError("Sanitized mutation must retain its permit and work digests")
        product_route = self.path in {
            "/v1/shops/{shop_id}/products.json",
            "/v1/shops/{shop_id}/products/{product_id}.json",
        }
        if product_route != (self.product_digest is not None):
            raise ValueError("Sanitized product call must retain one product digest")
        return self


class SanitizedProviderCounts(_ClosedModel):
    artwork_upload_count: StrictInt = Field(ge=0, le=1)
    product_post_count: StrictInt = Field(ge=0, le=1)
    product_put_count: StrictInt = Field(ge=0, le=2)
    product_get_count: StrictInt = Field(ge=0, le=100)
    forbidden_attempt_count: Literal[0]
    publish_attempt_count: Literal[0]
    order_attempt_count: Literal[0]
    fulfillment_attempt_count: Literal[0]
    final_state: ProviderFinalState


class SanitizedCommandObservation(_ClosedModel):
    name: ProviderCommandName
    outcome: ProviderCommandOutcome
    actor_digest: Digest
    expected_record_version: StrictInt = Field(ge=0)
    decision_digest: Digest | None = None

    @model_validator(mode="after")
    def only_the_winner_has_a_durable_decision(self) -> SanitizedCommandObservation:
        if (self.outcome is ProviderCommandOutcome.WON) != (self.decision_digest is not None):
            raise ValueError("Only the winning command may bind a durable decision")
        return self


class SanitizedProviderFacts(_ClosedModel):
    job_state: Literal["approved", "cancelled", "nonterminal"]
    source_size_bytes: StrictInt | None = Field(default=None, gt=0)
    same_job_strands_joined: StrictBool
    gemma_inference_count: StrictInt = Field(ge=0, le=4)
    agent_evidence_valid: StrictBool
    artwork_analysis_valid: StrictBool
    product_sync_valid: StrictBool
    seller_command_channel: StrictBool
    command_count: StrictInt = Field(ge=0, le=8)
    command_winner_count: StrictInt = Field(ge=0, le=8)
    durable_effect_count: StrictInt = Field(ge=0, le=8)
    consumed_permit_count: StrictInt = Field(ge=0, le=32)
    retired_permit_count: StrictInt = Field(ge=0, le=32)
    available_permit_count: StrictInt = Field(ge=0, le=32)
    remaining_execution_count: StrictInt = Field(ge=0, le=100)
    administrator_action_count: Literal[0]
    root_action_count: Literal[0]
    active_work_count: StrictInt = Field(ge=0, le=64)
    inventory_complete: Literal[True]


class SanitizedProviderObservation(_ClosedModel):
    format: Literal["phase6.6-sanitized-provider-observation-v1"]
    result: Literal["passed"]
    gate_id: ProviderGateId
    recorded_at: CanonicalTimestamp
    manifest_digest: Digest
    source_commit_digest: Digest
    deployment_digest: Digest
    deployment_authority_sha256: Digest
    agentcore_authority_digest: Digest
    agentcore_authority_sha256: Digest
    run_digest: Digest
    run_gate_digest: Digest
    provider_write_gate_digest: Digest
    actor_digest: Digest
    job_digest: Digest
    work_digest: Digest | None = None
    correlation_digest: Digest | None = None
    durable_digest: Digest
    calls: tuple[SanitizedProviderCall, ...] = Field(max_length=200)
    commands: tuple[SanitizedCommandObservation, ...] = Field(max_length=8)
    provider_counts: SanitizedProviderCounts
    facts: SanitizedProviderFacts

    @model_validator(mode="after")
    def counts_match_the_sanitized_ledger(self) -> SanitizedProviderObservation:
        calls = _call_counts(self.calls)
        if (
            calls["artwork"] != self.provider_counts.artwork_upload_count
            or calls["post"] != self.provider_counts.product_post_count
            or calls["put"] != self.provider_counts.product_put_count
            or calls["get"] != self.provider_counts.product_get_count
            or len(self.commands) != self.facts.command_count
            or sum(command.outcome is ProviderCommandOutcome.WON for command in self.commands)
            != self.facts.command_winner_count
            or self.manifest_digest != phase66_manifest_digest()
            or self.run_gate_digest == self.provider_write_gate_digest
        ):
            raise ValueError("Sanitized provider ledger counters are inconsistent")
        return self


class ProviderCanaryRequest(_ClosedModel):
    """Secret-free request passed to the separately implemented live adapter."""

    gate_id: ProviderGateId
    run_digest: Digest
    deployment_digest: Digest
    agentcore_authority_digest: Digest
    source_commit_digest: Digest
    approved_max_artwork_uploads: StrictInt = Field(ge=0, le=1)
    approved_max_product_posts: StrictInt = Field(ge=0, le=1)
    approved_max_product_puts: StrictInt = Field(ge=0, le=2)


class ProviderAcceptanceBackend(Protocol):
    """Live adapter boundary.  Implementations may perform exactly the authorized canary."""

    def run(self, request: ProviderCanaryRequest) -> ProviderLiveResult: ...


@dataclass(frozen=True, slots=True)
class _DeploymentAuthority:
    digest: str
    file_sha256: str
    source_commit_digest: str
    captured_at: datetime


@dataclass(frozen=True, slots=True)
class _AgentCoreAuthority:
    digest: str
    file_sha256: str
    captured_at: datetime


@dataclass(frozen=True, slots=True)
class _AuthorityBundle:
    gate_id: str
    deployment: _DeploymentAuthority
    agentcore: _AgentCoreAuthority
    run_gate: ProviderGateAuthority
    run_gate_digest: str
    write_gate: ProviderGateAuthority
    write_gate_digest: str
    prerequisite_records: tuple[Any, ...]
    run_digest: str


def _canonical(value: object, *, pretty: bool = False) -> bytes:
    return (
        json.dumps(
            value,
            allow_nan=False,
            ensure_ascii=True,
            indent=2 if pretty else None,
            separators=(",", ": ") if pretty else (",", ":"),
            sort_keys=True,
        )
        + ("\n" if pretty else "")
    ).encode("utf-8")


def _digest(value: object) -> str:
    return sha256(_canonical(value)).hexdigest()


def _parse_timestamp(value: str) -> datetime:
    if type(value) is not str or _TIMESTAMP.fullmatch(value) is None:
        raise ValueError("Timestamp is not canonical UTC RFC3339")
    return datetime.strptime(value, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=UTC)


def _timestamp(value: datetime) -> str:
    if not isinstance(value, datetime) or value.tzinfo is None or value.utcoffset() is None:
        raise ValueError("Timestamp must be timezone-aware")
    return value.astimezone(UTC).replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ")


def _strict_json(payload: bytes) -> object:
    def unique_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        value: dict[str, Any] = {}
        for key, nested in pairs:
            if key in value:
                raise ValueError("Duplicate JSON member")
            value[key] = nested
        return value

    def reject_constant(_value: str) -> None:
        raise ValueError("Non-finite JSON value")

    return json.loads(payload, object_pairs_hook=unique_object, parse_constant=reject_constant)


def _private_path(path: Path) -> Path:
    candidate = Path(os.path.abspath(path))
    try:
        relative = candidate.relative_to(PRIVATE_ROOT)
    except ValueError:
        raise ProviderAcceptanceError(
            "Provider acceptance paths must stay in the repository-private root"
        ) from None
    if not relative.parts:
        raise ProviderAcceptanceError("Provider acceptance path must name one private child")
    return candidate


def _require_private_chain(path: Path, *, create: bool) -> None:
    root = Path(os.path.abspath(REPOSITORY_ROOT))
    current = root
    if not stat.S_ISDIR(root.lstat().st_mode) or stat.S_ISLNK(root.lstat().st_mode):
        raise ProviderAcceptanceError("Repository root is not a stable directory")
    for component in path.relative_to(root).parts:
        current /= component
        try:
            metadata = current.lstat()
        except FileNotFoundError:
            if not create:
                raise ProviderAcceptanceError("Private authority directory is missing") from None
            current.mkdir(mode=0o700)
            metadata = current.lstat()
        if not stat.S_ISDIR(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode):
            raise ProviderAcceptanceError("Private authority path contains a non-directory")
        if metadata.st_mode & 0o077:
            if create:
                current.chmod(0o700)
            else:
                raise ProviderAcceptanceError("Private authority directory is not owner-only")


def _read_private_json(path: Path, expected_sha256: str, label: str) -> object:
    if _DIGEST.fullmatch(expected_sha256) is None:
        raise ProviderAcceptanceError(f"{label} SHA-256 is invalid")
    candidate = _private_path(path)
    _require_private_chain(candidate.parent, create=False)
    try:
        before = candidate.lstat()
        if (
            not stat.S_ISREG(before.st_mode)
            or stat.S_ISLNK(before.st_mode)
            or before.st_nlink != 1
            or before.st_mode & 0o077
            or not 1 <= before.st_size <= MAX_INPUT_BYTES
        ):
            raise OSError
        descriptor = os.open(candidate, os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW)
        try:
            chunks: list[bytes] = []
            remaining = before.st_size + 1
            while remaining:
                chunk = os.read(descriptor, min(remaining, 1024 * 1024))
                if not chunk:
                    break
                chunks.append(chunk)
                remaining -= len(chunk)
            payload = b"".join(chunks)
            after = os.fstat(descriptor)
        finally:
            os.close(descriptor)
    except OSError:
        raise ProviderAcceptanceError(
            f"{label} must be one stable mode-0600 private regular file"
        ) from None
    if (
        len(payload) != before.st_size
        or (before.st_dev, before.st_ino, before.st_size, before.st_mtime_ns, before.st_ctime_ns)
        != (after.st_dev, after.st_ino, after.st_size, after.st_mtime_ns, after.st_ctime_ns)
        or not secrets.compare_digest(sha256(payload).hexdigest(), expected_sha256)
    ):
        raise ProviderAcceptanceError(f"{label} changed or does not match its SHA-256")
    try:
        return _strict_json(payload)
    except (TypeError, UnicodeError, ValueError):
        raise ProviderAcceptanceError(f"{label} is not strict JSON") from None


def _write_private_once(path: Path, payload: bytes) -> str:
    candidate = _private_path(path)
    _require_private_chain(candidate.parent, create=True)
    descriptor: int | None = None
    try:
        descriptor = os.open(
            candidate,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC | os.O_NOFOLLOW,
            0o600,
        )
        with os.fdopen(descriptor, "wb", closefd=True) as stream:
            descriptor = None
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        candidate.chmod(0o600)
    except OSError:
        raise ProviderAcceptanceError(
            "Provider acceptance output must be fresh and owner-only"
        ) from None
    finally:
        if descriptor is not None:
            os.close(descriptor)
    return sha256(payload).hexdigest()


@contextmanager
def _reserved_private_output(path: Path) -> Iterator[tuple[Path, int]]:
    """Reserve a create-only output before any externally mutating backend can be built."""

    candidate = _private_path(path)
    _require_private_chain(candidate.parent, create=True)
    descriptor: int | None = None
    committed = False
    try:
        descriptor = os.open(
            candidate,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC | os.O_NOFOLLOW,
            0o600,
        )
        yield candidate, descriptor
        os.fsync(descriptor)
        candidate.chmod(0o600)
        committed = True
    except OSError:
        raise ProviderAcceptanceError(
            "Provider observation output must be fresh and owner-only"
        ) from None
    finally:
        if descriptor is not None:
            opened = os.fstat(descriptor)
            os.close(descriptor)
            if not committed:
                try:
                    current = candidate.lstat()
                    if (opened.st_dev, opened.st_ino) == (current.st_dev, current.st_ino):
                        candidate.unlink()
                except FileNotFoundError:
                    pass


def _deployment_authority(value: object, file_sha256: str) -> _DeploymentAuthority:
    try:
        if not isinstance(value, Mapping) or set(value) != {
            "authority",
            "captured_at",
            "deployment_digest",
            "format",
        }:
            raise ValueError
        authority = value["authority"]
        if not isinstance(authority, Mapping):
            raise ValueError
        deployment_digest = value["deployment_digest"]
        source_digest = authority.get("source_commit_digest")
        if (
            value["format"] != deployment_capture.FORMAT
            or not isinstance(deployment_digest, str)
            or deployment_digest != _digest(authority)
            or not isinstance(source_digest, str)
            or _DIGEST.fullmatch(source_digest) is None
            or authority.get("stack_name") != deployment_capture.EXPECTED_STACK_NAME
            or authority.get("region") != deployment_capture.EXPECTED_REGION
            or authority.get("readiness") != deployment_capture.EXPECTED_READINESS
        ):
            raise ValueError
        lambdas = authority.get("lambdas")
        if not isinstance(lambdas, list):
            raise ValueError
        if len(lambdas) != len(deployment_capture._FUNCTION_LOGICAL_IDS):
            raise ValueError
        logical_ids = {
            record.get("logical_id")
            for record in lambdas
            if isinstance(record, Mapping)
            and set(record)
            == {
                "code_sha256",
                "configuration_digest",
                "last_update_status",
                "logical_id",
                "release_fingerprint_digest",
                "state",
            }
        }
        if logical_ids != set(deployment_capture._FUNCTION_LOGICAL_IDS) or any(
            not isinstance(record, Mapping)
            or any(
                _DIGEST.fullmatch(str(record.get(name))) is None
                for name in (
                    "code_sha256",
                    "configuration_digest",
                    "release_fingerprint_digest",
                )
            )
            or record.get("state") != "Active"
            or record.get("last_update_status") != "Successful"
            for record in lambdas
        ):
            raise ValueError
        expected_release_digest = sha256(
            agentcore_capture.EXPECTED_CLOSURE_RELEASE_FINGERPRINT.encode("ascii")
        ).hexdigest()
        closure = {
            record.get("logical_id"): record
            for record in lambdas
            if isinstance(record, Mapping) and record.get("logical_id") in _CLOSURE_FUNCTIONS
        }
        if set(closure) != _CLOSURE_FUNCTIONS or any(
            record.get("release_fingerprint_digest") != expected_release_digest
            or record.get("state") != "Active"
            or record.get("last_update_status") != "Successful"
            for record in closure.values()
        ):
            raise ValueError
        captured_at = _parse_timestamp(value["captured_at"])
    except (KeyError, TypeError, ValueError):
        raise ProviderAcceptanceError(
            "Deployment authority does not bind the exact artwork-closure runtime"
        ) from None
    return _DeploymentAuthority(
        digest=deployment_digest,
        file_sha256=file_sha256,
        source_commit_digest=source_digest,
        captured_at=captured_at,
    )


def _agentcore_authority(value: object, file_sha256: str) -> _AgentCoreAuthority:
    try:
        if not isinstance(value, Mapping):
            raise ValueError
        agentcore_capture._validate_document(value)
        authority_digest = value.get("authority_digest")
        if not isinstance(authority_digest, str):
            raise ValueError
        captured_at = _parse_timestamp(value["captured_at"])
    except (KeyError, TypeError, ValueError):
        raise ProviderAcceptanceError(
            "AgentCore authority does not bind the exact artwork-closure runtime"
        ) from None
    return _AgentCoreAuthority(
        digest=authority_digest,
        file_sha256=file_sha256,
        captured_at=captured_at,
    )


def _prerequisites(
    value: object,
    *,
    gate_id: str,
    deployment: _DeploymentAuthority,
) -> tuple[Any, ...]:
    if not isinstance(value, list):
        raise ProviderAcceptanceError("Provider prerequisites must be one evidence-record array")
    gate = next(item for item in phase66_acceptance_manifest().gates if item.gate_id == gate_id)
    expected = gate.prerequisites
    records: list[Any] = []
    try:
        for nested in value:
            record = validate_phase66_evidence(nested)
            if (
                record.outcome is not AcceptanceOutcome.PASSED
                or getattr(record, "deployment_digest", None) != deployment.digest
                or record.source_commit_digest != deployment.source_commit_digest
            ):
                raise ValueError
            records.append(record)
    except (TypeError, ValueError):
        raise ProviderAcceptanceError(
            "Provider prerequisites do not bind the passed deployment/source"
        ) from None
    by_gate = {record.gate_id: record for record in records}
    if (
        len(by_gate) != len(records)
        or set(by_gate) != set(expected)
        or any(record.recorded_at < deployment.captured_at for record in records)
    ):
        raise ProviderAcceptanceError("Provider prerequisites are not the exact frozen gate set")
    return tuple(by_gate[gate_name] for gate_name in expected)


def _gate_authority(value: object, label: str) -> ProviderGateAuthority:
    try:
        return ProviderGateAuthority.model_validate(value)
    except (TypeError, ValidationError, ValueError):
        raise ProviderAcceptanceError(
            f"{label} does not match the closed authority contract"
        ) from None


def _load_authority_bundle(
    *,
    gate_id: str,
    deployment_authority_path: Path,
    deployment_authority_sha256: str,
    agentcore_authority_path: Path,
    agentcore_authority_sha256: str,
    prerequisite_records_path: Path,
    prerequisite_records_sha256: str,
    run_gate_path: Path,
    run_gate_sha256: str,
    provider_write_gate_path: Path,
    provider_write_gate_sha256: str,
) -> _AuthorityBundle:
    if gate_id not in _PROVIDER_GATES:
        raise ProviderAcceptanceError("Provider gate is not one frozen Phase 6.6 gate")
    paths = (
        deployment_authority_path,
        agentcore_authority_path,
        prerequisite_records_path,
        run_gate_path,
        provider_write_gate_path,
    )
    if len({_private_path(path) for path in paths}) != len(paths):
        raise ProviderAcceptanceError("Provider authority inputs must be distinct files")
    deployment = _deployment_authority(
        _read_private_json(
            deployment_authority_path,
            deployment_authority_sha256,
            "deployment authority",
        ),
        deployment_authority_sha256,
    )
    agentcore = _agentcore_authority(
        _read_private_json(
            agentcore_authority_path,
            agentcore_authority_sha256,
            "AgentCore authority",
        ),
        agentcore_authority_sha256,
    )
    prerequisites = _prerequisites(
        _read_private_json(
            prerequisite_records_path,
            prerequisite_records_sha256,
            "prerequisite records",
        ),
        gate_id=gate_id,
        deployment=deployment,
    )
    run_gate = _gate_authority(
        _read_private_json(run_gate_path, run_gate_sha256, "run gate"),
        "run gate",
    )
    write_gate = _gate_authority(
        _read_private_json(
            provider_write_gate_path,
            provider_write_gate_sha256,
            "provider write gate",
        ),
        "provider write gate",
    )
    prerequisite_digests = tuple(record.run_digest for record in prerequisites)
    common = {
        "gate_id": gate_id,
        "deployment_digest": deployment.digest,
        "deployment_authority_sha256": deployment.file_sha256,
        "agentcore_authority_digest": agentcore.digest,
        "agentcore_authority_sha256": agentcore.file_sha256,
        "source_commit_digest": deployment.source_commit_digest,
        "principal_digest": _EXPECTED_CALLER_DIGEST,
        "prerequisite_run_digests": list(prerequisite_digests),
    }
    for authority, kind in (
        (run_gate, ProviderGateKind.RUN),
        (write_gate, ProviderGateKind.WRITE),
    ):
        rendered = authority.model_dump(mode="json")
        if authority.gate_kind is not kind or any(
            rendered[name] != expected for name, expected in common.items()
        ):
            raise ProviderAcceptanceError("Provider gates do not bind one exact authority set")
        issued = _parse_timestamp(authority.issued_at)
        if issued < max(
            deployment.captured_at,
            agentcore.captured_at,
            *(record.recorded_at for record in prerequisites),
        ):
            raise ProviderAcceptanceError("Provider gate predates a required authority")
    if (
        run_gate_sha256 == provider_write_gate_sha256
        or run_gate.nonce_digest == write_gate.nonce_digest
        or (run_gate.issued_at, run_gate.expires_at)
        != (write_gate.issued_at, write_gate.expires_at)
        or run_gate.model_dump(mode="json", exclude={"gate_kind", "nonce_digest"})
        != write_gate.model_dump(mode="json", exclude={"gate_kind", "nonce_digest"})
    ):
        raise ProviderAcceptanceError("Provider run and write gates are not independent peers")
    run_digest = _digest(
        {
            "contract": "phase6.6-provider-canary-run-v1",
            "gate_id": gate_id,
            "deployment_digest": deployment.digest,
            "agentcore_authority_digest": agentcore.digest,
            "source_commit_digest": deployment.source_commit_digest,
            "run_gate_digest": run_gate_sha256,
            "provider_write_gate_digest": provider_write_gate_sha256,
            "prerequisite_run_digests": prerequisite_digests,
        }
    )
    return _AuthorityBundle(
        gate_id=gate_id,
        deployment=deployment,
        agentcore=agentcore,
        run_gate=run_gate,
        run_gate_digest=run_gate_sha256,
        write_gate=write_gate,
        write_gate_digest=provider_write_gate_sha256,
        prerequisite_records=prerequisites,
        run_digest=run_digest,
    )


def _call_counts(calls: Sequence[Any]) -> dict[str, int]:
    normalized = tuple(
        (
            call.audit.method if isinstance(call, ProviderLiveCall) else call.method,
            call.audit.path if isinstance(call, ProviderLiveCall) else call.path,
        )
        for call in calls
    )
    return {
        "artwork": sum(
            method == "POST" and path == "/v1/uploads/images.json" for method, path in normalized
        ),
        "post": sum(
            method == "POST" and path == "/v1/shops/{shop_id}/products.json"
            for method, path in normalized
        ),
        "put": sum(
            method == "PUT" and path == "/v1/shops/{shop_id}/products/{product_id}.json"
            for method, path in normalized
        ),
        "get": sum(
            method == "GET" and path == "/v1/shops/{shop_id}/products/{product_id}.json"
            for method, path in normalized
        ),
    }


def _active_work_count(work_requests: Sequence[WorkRequest]) -> int:
    return sum(
        work.status
        in {WorkRequestStatus.PENDING, WorkRequestStatus.CLAIMED, WorkRequestStatus.DISPATCHED}
        for work in work_requests
    )


def _analysis_is_valid(result: ProviderLiveResult) -> bool:
    analysis = result.artwork_analysis
    if analysis is None:
        return False
    material = {
        "job_id": analysis.job_id,
        "source_artifact_fingerprint": analysis.source_artifact_fingerprint,
        "analysis": analysis.analysis.model_dump(mode="json"),
    }
    return (
        analysis.job_id == result.job.job_id
        and analysis.analysis_id == result.job.artwork_analysis_id
        and analysis.fingerprint == result.job.artwork_analysis_fingerprint
        and analysis.source_artifact_fingerprint == result.job.source_artifact_fingerprint
        and analysis.fingerprint == canonical_fingerprint(material)
        and result.agent_evidence is not None
        and analysis.work_request_id == result.agent_evidence.work_request_id
        and analysis.work_request_id in {work.work_request_id for work in result.work_requests}
    )


def _agent_is_valid(result: ProviderLiveResult) -> bool:
    evidence = result.agent_evidence
    return bool(
        evidence is not None
        and evidence.job_id == result.job.job_id
        and evidence.evidence_id == result.job.agent_evidence_id
        and evidence.fingerprint == result.job.agent_evidence_fingerprint
        and evidence.fingerprint == evidence.authority_fingerprint
        and evidence.controller_model_id
        == agentcore_capture._expected_runtime_environment()[
            "MR_LISTER_STRANDS_CONTROLLER_MODEL_ID"
        ]
        and evidence.work_request_id
        in {
            work.work_request_id
            for work in result.work_requests
            if work.work_type is WorkType.PREPARE
        }
        and evidence.correlation_id == result.agentcore_correlation_id
        and evidence.publication_authorized is False
    )


def _sync_is_valid(result: ProviderLiveResult) -> bool:
    sync = result.product_sync
    return bool(
        sync is not None
        and sync.job_id == result.job.job_id
        and sync.sync_id == result.job.product_sync_id
        and sync.product_id == result.job.product_id
        and sync.image_id == result.job.uploaded_image_id
        and sync.review_version == result.job.synchronized_review_version
        and sync.payload_fingerprint == result.job.provider_payload_fingerprint
        and sync.fingerprint == result.job.product_sync_fingerprint
        and sync.fingerprint == product_sync_record_fingerprint(sync)
        and not sync.provider_locked
        and not sync.provider_published
    )


def _source_is_valid(result: ProviderLiveResult) -> bool:
    source = result.source_artifact
    return bool(
        source is not None
        and source.job_id == result.job.job_id
        and source.owner_id == result.job.owner_id
        and source.fingerprint == result.job.source_artifact_fingerprint
        and source.size_bytes == result.source_size_bytes
    )


def _validate_command_evidence(
    result: ProviderLiveResult,
    *,
    expected: ProviderCommandName,
) -> None:
    receipts = {receipt.receipt_id: receipt for receipt in result.command_receipts}
    decisions: tuple[ReviewDecisionRecord | CancellationDecisionRecord, ...] = (
        *result.review_decisions,
        *result.cancellation_decisions,
    )
    if (
        len(receipts) != 1
        or len(result.command_receipts) != 1
        or len(decisions) != 1
        or any(
            receipt.owner_id != result.job.owner_id
            or receipt.job_id != result.job.job_id
            or receipt.response.job_id != result.job.job_id
            or (
                receipt.work_request_id is not None
                and receipt.work_request_id
                not in {work.work_request_id for work in result.work_requests}
            )
            for receipt in result.command_receipts
        )
        or any(
            decision.job_id != result.job.job_id
            or decision.actor_owner_id != result.job.owner_id
            or decision.command_receipt_id not in receipts
            for decision in decisions
        )
    ):
        raise ProviderAcceptanceError("Provider command lacks one durable seller decision")
    decision = decisions[0]
    receipt = receipts[decision.command_receipt_id]
    if expected is ProviderCommandName.CANCEL:
        valid = (
            isinstance(decision, CancellationDecisionRecord)
            and not result.review_decisions
            and receipt.command_type == "cancel_job"
            and receipt.response.state is ControlJobState.CANCELLED
            and receipt.work_request_id is None
            and (
                not result.command_outcomes
                or decision.expected_record_version
                == next(
                    command.expected_record_version
                    for command in result.command_outcomes
                    if command.outcome is ProviderCommandOutcome.WON
                )
            )
        )
    else:
        review_decision = (
            ReviewDecision.REVISE
            if expected is ProviderCommandName.REVISE
            else ReviewDecision.APPROVE
        )
        command_type = (
            "revise_listing" if expected is ProviderCommandName.REVISE else "approve_review"
        )
        valid = (
            isinstance(decision, ReviewDecisionRecord)
            and not result.cancellation_decisions
            and decision.decision is review_decision
            and receipt.command_type == command_type
            and (
                review_decision is not ReviewDecision.APPROVE
                or (
                    receipt.response.state is ControlJobState.APPROVED
                    and receipt.work_request_id is None
                    and decision.decision_id == result.job.approval_decision_id
                    and decision.review_version == result.job.review_version
                    and decision.review_fingerprint == result.job.review_fingerprint
                    and decision.approval_fingerprint == result.job.approval_fingerprint
                )
            )
        )
    if not valid:
        raise ProviderAcceptanceError("Provider command decision changed the winning operation")


def _validate_live_result(result: ProviderLiveResult, authority: _AuthorityBundle) -> None:
    if result.gate_id != authority.gate_id:
        raise ProviderAcceptanceError("Live provider result changed the authorized gate")
    observed = result.observed_at.astimezone(UTC)
    if not (
        _parse_timestamp(authority.run_gate.issued_at)
        <= observed
        <= _parse_timestamp(authority.run_gate.expires_at)
    ):
        raise ProviderAcceptanceError("Live provider result is outside its exact gate window")
    if (
        result.aws_caller_arn != agentcore_capture.EXPECTED_CALLER_ARN
        or result.aws_caller_arn.endswith(":root")
        or result.seller_actor_owner_id != result.job.owner_id
        or not result.seller_command_channel
        or result.root_action_count
        or result.administrator_action_count
        or result.publication_attempt_count
        or result.order_attempt_count
        or result.fulfillment_attempt_count
        or result.job.publication_aggregate_id is not None
        or result.job.publication_terminal_state is not None
        or result.job.publication_result_id is not None
    ):
        raise ProviderAcceptanceError("Live provider result crossed the Phase 6 authority boundary")
    if tuple(call.ordinal for call in result.provider_calls) != tuple(
        range(1, len(result.provider_calls) + 1)
    ):
        raise ProviderAcceptanceError("Provider call ledger is not one exact ordered sequence")
    work_ids = {work.work_request_id for work in result.work_requests}
    if len(work_ids) != len(result.work_requests) or any(
        work.job_id != result.job.job_id or work.owner_id != result.job.owner_id
        for work in result.work_requests
    ):
        raise ProviderAcceptanceError("Durable work inventory changed job or seller authority")
    permits = {permit.attempt_id: permit for permit in result.provider_call_permits}
    if len(permits) != len(result.provider_call_permits) or any(
        permit.job_id != result.job.job_id or permit.work_request_id not in work_ids
        for permit in result.provider_call_permits
    ):
        raise ProviderAcceptanceError("Provider permit inventory changed job authority")
    mutation_calls = [
        call for call in result.provider_calls if call.audit.method in {"POST", "PUT"}
    ]
    mutation_attempts = {call.attempt_id for call in mutation_calls}
    if len(mutation_attempts) != len(mutation_calls):
        raise ProviderAcceptanceError("Provider mutation reused one call permit")
    for call in mutation_calls:
        permit = permits.get(call.attempt_id)
        if (
            permit is None
            or permit.status is not ProviderCallPermitStatus.CONSUMED
            or permit.work_request_id != call.work_request_id
            or permit.consumed_work_request_id != call.work_request_id
            or call.work_request_id not in work_ids
        ):
            raise ProviderAcceptanceError("Provider mutation lacks one consumed durable permit")
    if any(
        permit.status is ProviderCallPermitStatus.CONSUMED
        and permit.attempt_id not in mutation_attempts
        for permit in result.provider_call_permits
    ):
        raise ProviderAcceptanceError("Consumed provider permit lacks one audited mutation")
    counts = _call_counts(result.provider_calls)
    limits = _EXPECTED_LIMITS[result.gate_id]
    if counts["artwork"] > limits[0] or counts["post"] > limits[1] or counts["put"] > limits[2]:
        raise ProviderAcceptanceError("Provider call ledger exceeds its exact write gate")
    if counts["artwork"]:
        if not _source_is_valid(result):
            raise ProviderAcceptanceError("Artwork upload lacks one exact durable source")
    elif result.source_artifact is not None or result.source_size_bytes is not None:
        raise ProviderAcceptanceError("Durable source lacks an audited artwork upload")

    if result.gate_id == "provider.primary_same_job_canary":
        _validate_primary(result, counts)
    elif result.gate_id == "provider.concurrency_canary":
        _validate_concurrency(result, counts)
    else:
        _validate_cancellation(result, counts)


def _validate_product_join(result: ProviderLiveResult, *, require_final_get: bool) -> None:
    sync = result.product_sync
    final = result.final_product
    if not _sync_is_valid(result) or sync is None or final is None:
        raise ProviderAcceptanceError("Provider product evidence is not one durable safe draft")
    product_calls = [call for call in result.provider_calls if call.product_id is not None]
    if (
        not product_calls
        or any(call.product_id != sync.product_id for call in product_calls)
        or final.product_id != sync.product_id
        or final.payload_fingerprint != sync.payload_fingerprint
        or (require_final_get and product_calls[-1].audit.method != "GET")
    ):
        raise ProviderAcceptanceError("Provider calls do not bind one final unpublished product")


def _validate_primary(result: ProviderLiveResult, counts: Mapping[str, int]) -> None:
    if (
        result.source_size_bytes != PRIMARY_SOURCE_BYTES
        or result.job.state is not ControlJobState.APPROVED
        or result.job.active_work_request_id is not None
        or result.gemma_inference_count != 1
        or not _analysis_is_valid(result)
        or not _agent_is_valid(result)
        or counts["artwork"] != 1
        or counts["post"] != 1
        or counts["put"] != 2
        or counts["get"] < 1
        or result.command_outcomes
        or result.running_execution_count
        or any(
            permit.status is ProviderCallPermitStatus.AVAILABLE
            for permit in result.provider_call_permits
        )
        or _active_work_count(result.work_requests)
    ):
        raise ProviderAcceptanceError(
            "Primary provider canary did not prove the exact same-job flow"
        )
    _validate_command_evidence(result, expected=ProviderCommandName.APPROVE)
    if result.review_decisions[0].decision_id != result.job.approval_decision_id:
        raise ProviderAcceptanceError("Primary approval decision changed durable authority")
    _validate_product_join(result, require_final_get=True)


def _validate_concurrency(result: ProviderLiveResult, counts: Mapping[str, int]) -> None:
    names = tuple(command.name for command in result.command_outcomes)
    versions = {command.expected_record_version for command in result.command_outcomes}
    if (
        len(result.command_outcomes) != 3
        or set(names) != set(ProviderCommandName)
        or len(set(names)) != 3
        or len(versions) != 1
        or sum(command.outcome is ProviderCommandOutcome.WON for command in result.command_outcomes)
        != 1
        or any(command.actor_owner_id != result.job.owner_id for command in result.command_outcomes)
        or counts["put"] > 1
        or result.running_execution_count
        or any(
            permit.status is ProviderCallPermitStatus.AVAILABLE
            for permit in result.provider_call_permits
        )
    ):
        raise ProviderAcceptanceError("Concurrency canary did not prove one three-command winner")
    winner = next(
        command.name
        for command in result.command_outcomes
        if command.outcome is ProviderCommandOutcome.WON
    )
    _validate_command_evidence(result, expected=winner)
    if any(call.product_id is not None for call in result.provider_calls):
        _validate_product_join(result, require_final_get=bool(counts["get"]))
    elif result.product_sync is not None or result.final_product is not None:
        raise ProviderAcceptanceError("Concurrency product evidence lacks an audited product call")


def _validate_cancellation(result: ProviderLiveResult, counts: Mapping[str, int]) -> None:
    if (
        result.job.state is not ControlJobState.CANCELLED
        or result.job.active_work_request_id is not None
        or counts != {"artwork": 0, "post": 0, "put": 0, "get": 0}
        or result.provider_calls
        or result.product_sync is not None
        or result.final_product is not None
        or result.source_size_bytes is not None
        or result.artwork_analysis is not None
        or result.agent_evidence is not None
        or result.agentcore_correlation_id is not None
        or result.gemma_inference_count
        or result.running_execution_count
        or _active_work_count(result.work_requests)
        or len(result.command_outcomes) != 1
        or result.command_outcomes[0].name is not ProviderCommandName.CANCEL
        or result.command_outcomes[0].outcome is not ProviderCommandOutcome.WON
        or result.command_outcomes[0].actor_owner_id != result.job.owner_id
        or any(
            permit.status is ProviderCallPermitStatus.AVAILABLE
            for permit in result.provider_call_permits
        )
    ):
        raise ProviderAcceptanceError(
            "Cancellation canary did not prove seller-only terminal cancellation"
        )
    _validate_command_evidence(result, expected=ProviderCommandName.CANCEL)


def _derived_digest(run_digest: str, kind: str, raw_value: str) -> str:
    return sha256(
        b"\0".join(
            (b"phase6.6-provider-id-v1", run_digest.encode(), kind.encode(), raw_value.encode())
        )
    ).hexdigest()


def _sanitize_result(result: ProviderLiveResult, authority: _AuthorityBundle) -> dict[str, object]:
    _validate_live_result(result, authority)
    actor_digest = _derived_digest(authority.run_digest, "actor", result.job.owner_id)
    job_digest = _derived_digest(authority.run_digest, "job", result.job.job_id)
    primary = result.gate_id == "provider.primary_same_job_canary"
    work_digest = (
        _derived_digest(authority.run_digest, "work", result.agent_evidence.work_request_id)
        if primary and result.agent_evidence is not None
        else None
    )
    correlation_digest = (
        _derived_digest(authority.run_digest, "correlation", result.agentcore_correlation_id)
        if primary and result.agentcore_correlation_id is not None
        else None
    )
    calls = []
    for call in result.provider_calls:
        calls.append(
            {
                "ordinal": call.ordinal,
                "method": call.audit.method,
                "path": call.audit.path,
                "status_code": call.status_code,
                "attempt_digest": (
                    _derived_digest(authority.run_digest, "attempt", call.attempt_id)
                    if call.attempt_id is not None
                    else None
                ),
                "work_digest": (
                    _derived_digest(authority.run_digest, "work", call.work_request_id)
                    if call.work_request_id is not None
                    else None
                ),
                "product_digest": (
                    _derived_digest(authority.run_digest, "product", call.product_id)
                    if call.product_id is not None
                    else None
                ),
            }
        )
    call_models = tuple(SanitizedProviderCall.model_validate(call) for call in calls)
    decision_digest = (
        _digest(
            {
                "contract": "phase6.6-provider-decision-v1",
                "run_digest": authority.run_digest,
                "decision": (
                    (*result.review_decisions, *result.cancellation_decisions)[0].model_dump(
                        mode="json"
                    )
                ),
            }
        )
        if result.command_outcomes
        else None
    )
    command_models = tuple(
        SanitizedCommandObservation(
            name=command.name,
            outcome=command.outcome,
            actor_digest=actor_digest,
            expected_record_version=command.expected_record_version,
            decision_digest=(
                decision_digest if command.outcome is ProviderCommandOutcome.WON else None
            ),
        )
        for command in result.command_outcomes
    )
    counts = _call_counts(call_models)
    final_state = (
        ProviderFinalState.UNPUBLISHED_UNLOCKED
        if result.final_product is not None
        else ProviderFinalState.NOT_CREATED
    )
    permit_counts = Counter(permit.status for permit in result.provider_call_permits)
    job_state = (
        result.job.state.value
        if result.job.state in {ControlJobState.APPROVED, ControlJobState.CANCELLED}
        else "nonterminal"
    )
    durable_digest = _digest(
        {
            "job": result.job.model_dump(mode="json"),
            "source": (
                result.source_artifact.model_dump(mode="json")
                if result.source_artifact is not None
                else None
            ),
            "work": [work.model_dump(mode="json") for work in result.work_requests],
            "analysis": (
                result.artwork_analysis.model_dump(mode="json")
                if result.artwork_analysis is not None
                else None
            ),
            "agent": (
                result.agent_evidence.model_dump(mode="json")
                if result.agent_evidence is not None
                else None
            ),
            "sync": (
                result.product_sync.model_dump(mode="json")
                if result.product_sync is not None
                else None
            ),
            "permits": [permit.model_dump(mode="json") for permit in result.provider_call_permits],
            "receipts": [receipt.model_dump(mode="json") for receipt in result.command_receipts],
            "review_decisions": [
                decision.model_dump(mode="json") for decision in result.review_decisions
            ],
            "cancellation_decisions": [
                decision.model_dump(mode="json") for decision in result.cancellation_decisions
            ],
        }
    )
    observation = SanitizedProviderObservation(
        format=OBSERVATION_FORMAT,
        result="passed",
        gate_id=result.gate_id,
        recorded_at=_timestamp(result.observed_at),
        manifest_digest=phase66_manifest_digest(),
        source_commit_digest=authority.deployment.source_commit_digest,
        deployment_digest=authority.deployment.digest,
        deployment_authority_sha256=authority.deployment.file_sha256,
        agentcore_authority_digest=authority.agentcore.digest,
        agentcore_authority_sha256=authority.agentcore.file_sha256,
        run_digest=authority.run_digest,
        run_gate_digest=authority.run_gate_digest,
        provider_write_gate_digest=authority.write_gate_digest,
        actor_digest=actor_digest,
        job_digest=job_digest,
        work_digest=work_digest,
        correlation_digest=correlation_digest,
        durable_digest=durable_digest,
        calls=call_models,
        commands=command_models,
        provider_counts=SanitizedProviderCounts(
            artwork_upload_count=counts["artwork"],
            product_post_count=counts["post"],
            product_put_count=counts["put"],
            product_get_count=counts["get"],
            forbidden_attempt_count=0,
            publish_attempt_count=0,
            order_attempt_count=0,
            fulfillment_attempt_count=0,
            final_state=final_state,
        ),
        facts=SanitizedProviderFacts(
            job_state=job_state,
            source_size_bytes=result.source_size_bytes,
            same_job_strands_joined=_agent_is_valid(result),
            gemma_inference_count=result.gemma_inference_count,
            agent_evidence_valid=_agent_is_valid(result),
            artwork_analysis_valid=_analysis_is_valid(result),
            product_sync_valid=_sync_is_valid(result),
            seller_command_channel=result.seller_command_channel,
            command_count=len(result.command_outcomes),
            command_winner_count=sum(
                command.outcome is ProviderCommandOutcome.WON for command in result.command_outcomes
            ),
            durable_effect_count=len(result.review_decisions) + len(result.cancellation_decisions),
            consumed_permit_count=permit_counts[ProviderCallPermitStatus.CONSUMED],
            retired_permit_count=permit_counts[ProviderCallPermitStatus.RETIRED],
            available_permit_count=permit_counts[ProviderCallPermitStatus.AVAILABLE],
            remaining_execution_count=result.running_execution_count,
            administrator_action_count=result.administrator_action_count,
            root_action_count=result.root_action_count,
            active_work_count=_active_work_count(result.work_requests),
            inventory_complete=True,
        ),
    )
    return observation.model_dump(mode="json")


def capture_phase66_provider_observation(
    *,
    gate_id: str,
    deployment_authority_path: Path,
    deployment_authority_sha256: str,
    agentcore_authority_path: Path,
    agentcore_authority_sha256: str,
    prerequisite_records_path: Path,
    prerequisite_records_sha256: str,
    run_gate_path: Path,
    run_gate_sha256: str,
    provider_write_gate_path: Path,
    provider_write_gate_sha256: str,
    output_path: Path,
    backend_factory: Callable[[], ProviderAcceptanceBackend],
) -> Mapping[str, object]:
    """Validate all local authority first, run one injected backend, and sanitize its result."""

    output = _private_path(output_path)
    authority = _load_authority_bundle(
        gate_id=gate_id,
        deployment_authority_path=deployment_authority_path,
        deployment_authority_sha256=deployment_authority_sha256,
        agentcore_authority_path=agentcore_authority_path,
        agentcore_authority_sha256=agentcore_authority_sha256,
        prerequisite_records_path=prerequisite_records_path,
        prerequisite_records_sha256=prerequisite_records_sha256,
        run_gate_path=run_gate_path,
        run_gate_sha256=run_gate_sha256,
        provider_write_gate_path=provider_write_gate_path,
        provider_write_gate_sha256=provider_write_gate_sha256,
    )
    if output in {
        _private_path(path)
        for path in (
            deployment_authority_path,
            agentcore_authority_path,
            prerequisite_records_path,
            run_gate_path,
            provider_write_gate_path,
        )
    }:
        raise ProviderAcceptanceError("Provider observation output collides with an authority")
    with _reserved_private_output(output) as (_reserved, descriptor):
        try:
            backend = backend_factory()
            result = ProviderLiveResult.model_validate(
                backend.run(
                    ProviderCanaryRequest(
                        gate_id=gate_id,
                        run_digest=authority.run_digest,
                        deployment_digest=authority.deployment.digest,
                        agentcore_authority_digest=authority.agentcore.digest,
                        source_commit_digest=authority.deployment.source_commit_digest,
                        approved_max_artwork_uploads=(
                            authority.write_gate.approved_max_artwork_uploads
                        ),
                        approved_max_product_posts=(
                            authority.write_gate.approved_max_product_posts
                        ),
                        approved_max_product_puts=authority.write_gate.approved_max_product_puts,
                    )
                )
            )
            observation = _sanitize_result(result, authority)
        except ProviderAcceptanceError:
            raise
        except Exception:
            raise ProviderAcceptanceError("Provider live adapter failed closed") from None
        payload = _canonical(observation, pretty=True)
        remaining = memoryview(payload)
        while remaining:
            written = os.write(descriptor, remaining)
            if written <= 0:
                raise ProviderAcceptanceError("Provider observation output write failed")
            remaining = remaining[written:]
        observation_sha256 = sha256(payload).hexdigest()
    return {
        "gate_id": gate_id,
        "observation_sha256": observation_sha256,
        "result": "passed",
        "run_digest": authority.run_digest,
    }


def _validate_sanitized_observation(
    value: object,
    *,
    authority: _AuthorityBundle,
) -> SanitizedProviderObservation:
    try:
        observation = SanitizedProviderObservation.model_validate(value)
    except (TypeError, ValidationError, ValueError):
        raise ProviderAcceptanceError(
            "Provider observation is not the closed sanitized contract"
        ) from None
    expected = {
        "gate_id": authority.gate_id,
        "source_commit_digest": authority.deployment.source_commit_digest,
        "deployment_digest": authority.deployment.digest,
        "deployment_authority_sha256": authority.deployment.file_sha256,
        "agentcore_authority_digest": authority.agentcore.digest,
        "agentcore_authority_sha256": authority.agentcore.file_sha256,
        "run_digest": authority.run_digest,
        "run_gate_digest": authority.run_gate_digest,
        "provider_write_gate_digest": authority.write_gate_digest,
    }
    rendered = observation.model_dump(mode="json")
    if any(rendered[name] != expected_value for name, expected_value in expected.items()):
        raise ProviderAcceptanceError("Provider observation changed its exact authority binding")
    recorded = _parse_timestamp(observation.recorded_at)
    if not (
        _parse_timestamp(authority.run_gate.issued_at)
        <= recorded
        <= _parse_timestamp(authority.run_gate.expires_at)
    ) or any(record.recorded_at > recorded for record in authority.prerequisite_records):
        raise ProviderAcceptanceError("Provider observation is outside its authority window")
    _require_sanitized_gate_facts(observation)
    return observation


def _require_sanitized_gate_facts(observation: SanitizedProviderObservation) -> None:
    counts = observation.provider_counts
    facts = observation.facts
    product_calls = tuple(call for call in observation.calls if call.product_digest is not None)
    if (
        counts.forbidden_attempt_count
        or counts.publish_attempt_count
        or counts.order_attempt_count
        or counts.fulfillment_attempt_count
        or facts.root_action_count
        or facts.administrator_action_count
        or not facts.seller_command_channel
        or not facts.inventory_complete
    ):
        raise ProviderAcceptanceError("Sanitized provider observation crossed the Phase 6 boundary")
    if observation.gate_id == "provider.primary_same_job_canary":
        if (
            facts.job_state != "approved"
            or facts.source_size_bytes != PRIMARY_SOURCE_BYTES
            or not facts.same_job_strands_joined
            or facts.gemma_inference_count != 1
            or not facts.agent_evidence_valid
            or not facts.artwork_analysis_valid
            or not facts.product_sync_valid
            or facts.command_count
            or facts.command_winner_count
            or facts.durable_effect_count != 1
            or facts.available_permit_count
            or facts.active_work_count
            or counts.artwork_upload_count != 1
            or counts.product_post_count != 1
            or counts.product_put_count != 2
            or counts.product_get_count < 1
            or counts.final_state is not ProviderFinalState.UNPUBLISHED_UNLOCKED
            or len({call.product_digest for call in product_calls}) != 1
            or not product_calls
            or product_calls[-1].method != "GET"
            or observation.commands
            or observation.work_digest is None
            or observation.correlation_digest is None
        ):
            raise ProviderAcceptanceError("Sanitized primary provider evidence is incomplete")
    elif observation.gate_id == "provider.concurrency_canary":
        command_names = tuple(command.name for command in observation.commands)
        command_versions = {command.expected_record_version for command in observation.commands}
        if (
            facts.command_count != 3
            or facts.command_winner_count != 1
            or facts.durable_effect_count != 1
            or set(command_names) != set(ProviderCommandName)
            or len(set(command_names)) != 3
            or len(command_versions) != 1
            or facts.available_permit_count
            or counts.product_put_count > 1
            or (product_calls and len({call.product_digest for call in product_calls}) != 1)
            or observation.work_digest is not None
            or observation.correlation_digest is not None
        ):
            raise ProviderAcceptanceError("Sanitized concurrency provider evidence is incomplete")
    elif (
        facts.job_state != "cancelled"
        or facts.command_count != 1
        or facts.command_winner_count != 1
        or facts.durable_effect_count != 1
        or len(observation.commands) != 1
        or observation.commands[0].name is not ProviderCommandName.CANCEL
        or observation.commands[0].outcome is not ProviderCommandOutcome.WON
        or facts.remaining_execution_count
        or facts.available_permit_count
        or facts.active_work_count
        or any(
            (
                counts.artwork_upload_count,
                counts.product_post_count,
                counts.product_put_count,
                counts.product_get_count,
            )
        )
        or counts.final_state is not ProviderFinalState.NOT_CREATED
        or observation.calls
        or observation.work_digest is not None
        or observation.correlation_digest is not None
    ):
        raise ProviderAcceptanceError("Sanitized cancellation provider evidence is incomplete")


def _assertion_values(observation: SanitizedProviderObservation) -> dict[str, tuple[object, int]]:
    counts = observation.provider_counts
    facts = observation.facts
    if observation.gate_id == "provider.primary_same_job_canary":
        return {
            "five_mib_upload_reaches_review": (
                {"source_size_bytes": facts.source_size_bytes, "job_state": facts.job_state},
                1,
            ),
            "same_job_strands_correlation_is_joined": (
                {
                    "job_digest": observation.job_digest,
                    "work_digest": observation.work_digest,
                    "correlation_digest": observation.correlation_digest,
                },
                1,
            ),
            "gemma_intelligence_under_strands_is_recorded": (
                {
                    "analysis_valid": facts.artwork_analysis_valid,
                    "agent_valid": facts.agent_evidence_valid,
                    "agentcore_authority_digest": observation.agentcore_authority_digest,
                    "gemma_inference_count": facts.gemma_inference_count,
                },
                1,
            ),
            "one_product_post_is_recorded": (counts.product_post_count, 1),
            "two_same_product_puts_are_recorded": (
                {
                    "put_count": counts.product_put_count,
                    "product_digests": sorted(
                        {call.product_digest for call in observation.calls if call.product_digest}
                    ),
                },
                2,
            ),
            "approval_ends_at_approved": (facts.job_state, 1),
            "final_product_is_unpublished_unlocked": (counts.final_state.value, 1),
            "forbidden_provider_attempt_count_is_zero": (0, 0),
        }
    if observation.gate_id == "provider.concurrency_canary":
        return {
            "three_commands_have_one_winner": (
                [command.model_dump(mode="json") for command in observation.commands],
                1,
            ),
            "one_decision_or_work_effect_is_recorded": (facts.durable_effect_count, 1),
            "at_most_one_product_put_is_recorded": (
                counts.product_put_count,
                counts.product_put_count,
            ),
            "forbidden_provider_attempt_count_is_zero": (0, 0),
        }
    return {
        "seller_cancel_reaches_cancelled": (facts.job_state, 1),
        "root_credentials_are_rejected": (
            {"administrator_actions": 0, "root_actions": 0},
            0,
        ),
        "no_phase6_execution_remains_running": (facts.remaining_execution_count, 0),
        "forbidden_provider_attempt_count_is_zero": (0, 0),
    }


def _artifact_document(
    observation: SanitizedProviderObservation,
    *,
    artifact_format: str,
) -> dict[str, object]:
    common = {
        "result": "passed",
        "gate": observation.gate_id,
        "run_digest": observation.run_digest,
        "deployment_digest": observation.deployment_digest,
        "agentcore_authority_digest": observation.agentcore_authority_digest,
        "recorded_at": observation.recorded_at,
    }
    if artifact_format == LEDGER_FORMAT:
        return {
            **common,
            "artifact_contract": LEDGER_FORMAT,
            "run_gate_digest": observation.run_gate_digest,
            "provider_write_gate_digest": observation.provider_write_gate_digest,
            "calls": [call.model_dump(mode="json") for call in observation.calls],
            "provider_counts": observation.provider_counts.model_dump(mode="json"),
        }
    if artifact_format == SUMMARY_FORMAT:
        return {
            **common,
            "artifact_contract": SUMMARY_FORMAT,
            "actor_digest": observation.actor_digest,
            "job_digest": observation.job_digest,
            "work_digest": observation.work_digest,
            "correlation_digest": observation.correlation_digest,
            "durable_digest": observation.durable_digest,
            "facts": observation.facts.model_dump(mode="json"),
            "commands": [command.model_dump(mode="json") for command in observation.commands],
            "provider_counts": observation.provider_counts.model_dump(mode="json"),
        }
    return {
        **common,
        "artifact_contract": LOG_AUDIT_FORMAT,
        "deployment_authority_sha256": observation.deployment_authority_sha256,
        "agentcore_authority_sha256": observation.agentcore_authority_sha256,
        "durable_digest": observation.durable_digest,
        "observation_digest": _digest(observation.model_dump(mode="json")),
        "forbidden_field_match_count": 0,
        "sensitive_value_match_count": 0,
        "free_text_value_count": 0,
    }


def _build_evidence_outputs(
    observation: SanitizedProviderObservation,
    authority: _AuthorityBundle,
) -> tuple[dict[str, bytes], dict[str, object]]:
    gate = next(
        item for item in phase66_acceptance_manifest().gates if item.gate_id == observation.gate_id
    )
    slug = observation.gate_id.rsplit(".", 1)[-1]
    artifact_specs: list[tuple[ArtifactKind, str, str]] = [
        (ArtifactKind.PROVIDER_CALL_LEDGER, f"{slug}-provider-ledger.json", LEDGER_FORMAT),
        (ArtifactKind.CANARY_SUMMARY, f"{slug}-canary-summary.json", SUMMARY_FORMAT),
    ]
    if ArtifactKind.LOG_AUDIT in gate.required_artifact_kinds:
        artifact_specs.append((ArtifactKind.LOG_AUDIT, f"{slug}-log-audit.json", LOG_AUDIT_FORMAT))
    outputs: dict[str, bytes] = {}
    artifacts: list[dict[str, object]] = []
    artifact_files: list[dict[str, object]] = []
    for kind, filename, contract in artifact_specs:
        contents = _canonical(
            _artifact_document(observation, artifact_format=contract), pretty=True
        )
        digest = sha256(contents).hexdigest()
        outputs[filename] = contents
        artifacts.append(
            {
                "kind": kind.value,
                "artifact_format": ArtifactFormat.JSON.value,
                "artifact_digest": digest,
                "byte_count": len(contents),
                "redaction_verified": True,
            }
        )
        artifact_files.append(
            Phase66ArtifactFile(
                artifact_digest=digest,
                kind=kind,
                artifact_format=ArtifactFormat.JSON,
                relative_path=filename,
            ).model_dump(mode="json")
        )
    assertion_values = _assertion_values(observation)
    if tuple(assertion_values) != gate.required_assertions:
        raise ProviderAcceptanceError("Provider evidence assertions drifted from the frozen gate")
    assertions = [
        {
            "assertion_id": assertion_id,
            "passed": True,
            "observation_digest": _digest(
                {
                    "assertion_id": assertion_id,
                    "run_digest": observation.run_digest,
                    "value": value,
                }
            ),
            "observed_count": count,
        }
        for assertion_id, (value, count) in assertion_values.items()
    ]
    counts = observation.provider_counts
    record = validate_phase66_evidence(
        {
            "schema_version": "6.6.0",
            "manifest_digest": phase66_manifest_digest(),
            "run_digest": observation.run_digest,
            "source_commit_digest": observation.source_commit_digest,
            "gate_id": observation.gate_id,
            "evidence_class": AcceptanceEvidenceClass.PROVIDER_DESTRUCTIVE.value,
            "outcome": AcceptanceOutcome.PASSED.value,
            "recorded_at": observation.recorded_at,
            "job_digest": observation.job_digest,
            "work_digest": observation.work_digest,
            "correlation_digest": observation.correlation_digest,
            "assertions": assertions,
            "artifacts": artifacts,
            "privacy": {
                "sanitizer_contract": "phase6.6-sanitized-evidence-v1",
                "forbidden_field_match_count": 0,
                "sensitive_value_match_count": 0,
                "free_text_value_count": 0,
            },
            "deployment_digest": observation.deployment_digest,
            "actor_digests": [observation.actor_digest],
            "provider_gate_attestation": {
                "run_gate_digest": authority.run_gate_digest,
                "provider_write_gate_digest": authority.write_gate_digest,
                "approved_scope": "unpublished_draft_create_update_only",
                "root_credentials_rejected": True,
                "publication_capability_absent": True,
                "approved_max_product_posts": authority.write_gate.approved_max_product_posts,
                "approved_max_product_puts": authority.write_gate.approved_max_product_puts,
            },
            "provider_call_summary": {
                "artwork_upload_count": counts.artwork_upload_count,
                "product_post_count": counts.product_post_count,
                "product_put_count": counts.product_put_count,
                "product_get_count": counts.product_get_count,
                "forbidden_attempt_count": 0,
                "publish_attempt_count": 0,
                "order_attempt_count": 0,
                "fulfillment_attempt_count": 0,
                "final_state": counts.final_state.value,
            },
            "moderated_session": None,
        }
    )
    record_value = record.model_dump(mode="json")
    outputs["records.json"] = _canonical([record_value], pretty=True)
    outputs["artifact-files.json"] = _canonical(artifact_files, pretty=True)
    return outputs, {
        "artifact_count": len(artifact_specs),
        "gate_id": observation.gate_id,
        "record_digest": _digest(record_value),
        "result": "passed",
        "run_digest": observation.run_digest,
    }


@contextmanager
def _staged_output_root(final_root: Path) -> Iterator[Path]:
    final = _private_path(final_root)
    _require_private_chain(final.parent, create=True)
    try:
        final.mkdir(mode=0o700)
    except FileExistsError:
        raise ProviderAcceptanceError("Provider evidence output root must be fresh") from None
    try:
        yield final
    except Exception:
        if final.exists() and not final.is_symlink():
            for child in final.iterdir():
                if child.is_file() and not child.is_symlink():
                    child.unlink()
            final.rmdir()
        raise


def prepare_phase66_provider_evidence(
    *,
    gate_id: str,
    deployment_authority_path: Path,
    deployment_authority_sha256: str,
    agentcore_authority_path: Path,
    agentcore_authority_sha256: str,
    prerequisite_records_path: Path,
    prerequisite_records_sha256: str,
    run_gate_path: Path,
    run_gate_sha256: str,
    provider_write_gate_path: Path,
    provider_write_gate_sha256: str,
    observation_path: Path,
    observation_sha256: str,
    output_root: Path,
) -> Mapping[str, object]:
    """Validate one sanitized canary observation and create its frozen evidence fragment."""

    authority = _load_authority_bundle(
        gate_id=gate_id,
        deployment_authority_path=deployment_authority_path,
        deployment_authority_sha256=deployment_authority_sha256,
        agentcore_authority_path=agentcore_authority_path,
        agentcore_authority_sha256=agentcore_authority_sha256,
        prerequisite_records_path=prerequisite_records_path,
        prerequisite_records_sha256=prerequisite_records_sha256,
        run_gate_path=run_gate_path,
        run_gate_sha256=run_gate_sha256,
        provider_write_gate_path=provider_write_gate_path,
        provider_write_gate_sha256=provider_write_gate_sha256,
    )
    observation = _validate_sanitized_observation(
        _read_private_json(observation_path, observation_sha256, "provider observation"),
        authority=authority,
    )
    outputs, summary = _build_evidence_outputs(observation, authority)
    with _staged_output_root(output_root) as staging:
        for filename, payload in outputs.items():
            _write_private_once(staging / filename, payload)
    return summary


__all__ = [
    "CommandRaceObservation",
    "FinalProductObservation",
    "ProviderAcceptanceBackend",
    "ProviderAcceptanceError",
    "ProviderCanaryRequest",
    "ProviderCommandName",
    "ProviderCommandOutcome",
    "ProviderGateAuthority",
    "ProviderGateKind",
    "ProviderLiveCall",
    "ProviderLiveResult",
    "SanitizedProviderObservation",
    "capture_phase66_provider_observation",
    "prepare_phase66_provider_evidence",
]
